{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 openapi: 3.1.0\
info:\
  title: LCPS Action\
  version: 1.0.0\
  description: API para acceder a datos de escuelas de LCPS\
servers:\
  - url: https://api.lcps.k12.nm.us\
    description: LCPS API Server\
paths:\
  /schools:\
    get:\
      operationId: getSchools\
      summary: Obtiene una lista de escuelas\
      description: Retorna un listado completo de escuelas disponibles en el sistema LCPS.\
      responses:\
        '200':\
          description: Lista de escuelas\
          content:\
            application/json:\
              schema:\
                type: array\
                items:\
                  type: object\
                  properties:\
                    id:\
                      type: integer\
                      example: 123\
                    name:\
                      type: string\
                      example: Vista Middle School\
                    address:\
                      type: string\
                      example: 123 School Ave\
}